version: '3'

services:
  rest_service:
    build: rest-service
    image: rest_service
    container_name: rest_service 
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
     - 8080:8080
    environment:
      RABBITMQ_HOST: "rabbitmq"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/q/health"]
      interval: 5s
      timeout: 30s
      retries: 10

  token_service:
    build: token-service
    image: token-service
    container_name: token-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: "rabbitmq"
    stop_grace_period: 1m

  rabbitmq:
    image: "rabbitmq:3.8"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "joe"
      RABBITMQ_DEFAULT_PASS: "mama"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 5s
      timeout: 30s
      retries: 10
